### ISSUE TITLE
Images sometimes failing with libarchive error 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/Community#805] opened 2023-09-14 18:30 UTC
Ran an image for vanilla, it failed with
```
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/opt/conda/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/opt/conda/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

Ran that exact same image again and it passed
Evidence here: https://repo.dit.maap-project.org/root/maap-workspaces/-/jobs/7080

@anilnatha experienced the same thing

**Comment by anilnatha** [comment] 2023-09-14 18:37
This is a very annoying build bug. In my experience, the bug wasn't encountered again by simply waiting for some time to pass even with no code changes, by rerunning the job. Sometimes I could rerun the job immediately, other times I would have to wait a few hours.

**Comment by anilnatha** [comment] 2023-09-18 21:07
@grallewellyn (fyi) A few moments ago I experienced this issue when trying to build an updated Pangeo image on my local machine. So this issue may not be due to an issue with our CI/CD.

Here is the output I saw from my local machine:

```
62.12   File "/opt/conda/bin/mamba", line 7, in <module>
62.12     from mamba.mamba import main
62.12   File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
62.12     import libmambapy as api
62.12   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
62.12     raise e
62.12   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
62.12     from libmambapy.bindings import *  # noqa: F401,F403
62.12     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
62.12 ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

**Comment by grallewellyn** [comment] 2023-10-09 21:32
So far, we have not seen this bug again with the recent change to use libmamba solver instead of mamba. This change is in develop. We can probably close out this ticket soon if we continue to not see this error

**Comment by gchang** [comment] 2023-10-12 20:37
Can't reliably reproduce, closing for now.

**Closed by gchang** 2023-10-12 20:37 UTC
Labels: ADE
