### ISSUE TITLE
Federated Token expired

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/Community#570] opened 2022-07-26 17:31 UTC
User tried to access DAAC data, but was getting FORBIDDEN. It seems like retrieving the S3 token from the DAAC was failing because the user's URS token expired. Was able to get it to work by logging out of Eclipse Che and going through the standard login, which seemed to refresh the token.

Is there a way to automatically refresh the federated URS token?

**Comment by gchang** [comment] 2022-11-10 21:59
Still valid, token can become stale in certain scenarios.

**Comment by sujen1412** [comment] 2023-08-03 20:39
Found out during HECC, not something users on MAAP are reporting.

**Comment by bsatoriu** [comment] 2023-09-28 21:45
Duplicate of #758

**Closed** 2023-09-28 21:45 UTC
Labels: JPL, API
